### ISSUE TITLE
[BUG]运行run-bot.bat报错 No module named 'pkg.openai'

### ISSUE THREAD

**Issue by pengxingyang02** [RockChinQ/qcg-installer#24]
**运行环境**
- 部署方式：
    手动部署 还是 自动部署
- 系统环境：
    e,g, Centos x64
- Python环境（仅手动部署填写）：
    e.g. Python 3.10.9

**描述漏洞**
主程序报错

**完整报错信息**
```
E:\bot\QChatGPT>..\python\python.exe main.py
Traceback (most recent call last):
  File "E:\bot\QChatGPT\main.py", line 103, in <module>
    main()
  File "E:\bot\QChatGPT\main.py", line 52, in main
    import pkg.openai.manager
ModuleNotFoundError: No module named 'pkg.openai'
```

**Comment by RockChinQ** [comment]
尝试 #15

**Comment by RockChinQ** [comment]
哦你这是不是文件不全啊，看看pkg目录下有什么文件

**Comment by RockChinQ** [comment]
系统上python环境过于复杂，建议手动部署或docker部署
