### ISSUE TITLE
[BUG] docker安装最后一步报错 命令：docker compose run -itd setup

### ISSUE THREAD

**Issue by lijie-jie** [RockChinQ/qcg-installer#26]
**运行环境**
- 部署方式：
    docker 部署
- 系统环境：
    e,g, Centos 7

**描述漏洞**
运行主程序时报错：docker compose run -itd setup

**完整报错信息**
加载禁用列表: person: [2854196310], group: [204785790]
加载插件
初始化插件
2023-02-08 09:10:45 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
WARNING: 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
2023-02-08 09:10:55 - ERROR    
ERROR: 
ERROR: 捕捉到未知异常:, 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 332, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 680, in __await_impl__
    await protocol.wait_closed()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/bot/main.py", line 185, in run_bot_wrapper
    raise e
  File "/bot/main.py", line 147, in run_bot_wrapper
    qqbot.bot.run()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 199, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 276, in run
    asyncio.run(self._run())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 240, in _run
    await self.startup()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by RockChinQ** [comment]
更换mirai-api-http的端口，但docker修改端口过于麻烦，建议手动部署

**Comment by lijie-jie** [comment]
好的，谢谢
