### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BZBY** [RockChinQ/qcg-installer#35]
**运行环境**
- 部署方式：
    手动部署 还是 自动部署
- 系统环境：
    e,g, win10
- Python环境（仅手动部署填写）：
    e.g. Python 3.10

**描述漏洞**
D:\Coding\chatgpt-Ai\Ai\QChatGPT>..\python\python.exe main.py
Database initialized.
[2023-03-10 21:52:02.563] keymgr.py (62) - [INFO] : 使用api-key:default
[2023-03-10 21:52:02.563] manager.py (30) - [INFO] : 文字总使用量：0
[2023-03-10 21:52:02.564] manager.py (95) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790, 691226829]
[2023-03-10 21:52:02.565] host.py (88) - [INFO] : 加载插件
[2023-03-10 21:52:02.567] host.py (105) - [INFO] : 初始化插件
2023-03-10 21:52:02 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-03-10 21:52:02.570] bot.py (260) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-03-10 21:52:14.579] main.py (261) - 

run.bot 启动之后一直卡住。。。

**完整报错信息**
完整的报错信息

**Comment by RockChinQ** [comment]
请提供完整控制台输出信息

**Comment by BZBY** [comment]
> 请提供完整控制台输出信息

这就是全部，mirr那正常

**Comment by BZBY** [comment]
> 请提供完整控制台输出信息

还是一样，昨天又开了还是一样，打开run_bot.bat就输出那些，然后就一动不动，是不是梯子的问题？不过我梯子关了还是不行

**Comment by BZBY** [comment]
://github.com/RockChinQ/QChatGPT/issues/37
[2023-03-11 08:59:23.485] main.py (297) - [INFO] : 当前已是最新版本
[2023-03-11 09:01:54.175] message.py (29) - [INFO] : [person_1765612509]发送消息:你骄傲
Exception in thread Thread-6 (run_until_complete):
Traceback (most recent call last):
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1055, in create_connection
    raise exceptions[0]
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1040, in create_connection
    sock = await self._connect_sock(
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 954, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 704, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 812, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 599, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 587, in arequest_raw
    result = await session.request(**request_kwargs)
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 899, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1231, in _create_proxy_connection
    transport, proto = await self._create_direct_connection(
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientProxyConnectionError: Cannot connect to host 127.0.0.1:7890 ssl:default [远程计算机拒绝网络连接。]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Coding\chatgpt-Ai\QChatGPT\pkg\openai\modelmgr.py", line 59, in __a_request__
    self.ret:dict = await self.request_fun(**kwargs)
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 300, in arequest
    result = await self.arequest_raw(
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 604, in arequest_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\Coding\chatgpt-Ai\QChatGPT\pkg\openai\modelmgr.py", line 63, in __a_request__
    raise ConnectionError(self.error_info)
ConnectionError: Error communicating with OpenAI
请检查网络连接或代理是否正常
[2023-03-11 09:01:56.314] message.py (126) - [ERROR] : Error communicating with OpenAI
请检查网络连接或代理是否正常
Traceback (most recent call last):
  File "D:\Coding\chatgpt-Ai\QChatGPT\pkg\qqbot\message.py", line 46, in process_normal_message
    text = session.append(text_message)
  File "D:\Coding\chatgpt-Ai\QChatGPT\pkg\openai\session.py", line 217, in append
    message = pkg.utils.context.get_openai_manager().request_completion(
  File "D:\Coding\chatgpt-Ai\QChatGPT\pkg\openai\manager.py", line 55, in request_completion
    ai.request(
  File "D:\Coding\chatgpt-Ai\QChatGPT\pkg\openai\modelmgr.py", line 128, in request
    self.ret_handle()
  File "D:\Coding\chatgpt-Ai\QChatGPT\pkg\openai\modelmgr.py", line 97, in ret_handle
    raise Exception(self.error_info)
Exception: Error communicating with OpenAI
请检查网络连接或代理是否正常
[2023-03-11 09:01:56.319] manager.py (337) - [INFO] : 通知管理员:person_1765612509会话处理异常:Error communicating with OpenAI
请检查网络连接或代理是否正常
[2023-03-11 09:01:56.324] process.py (155) - [INFO] : 回复[person_1765612509]文字消息:[bot]err:Error communicating with OpenAI
请检查网络连接或代理是否正常
Exception in thread Thread-7 (run):
Traceback (most recent call last):
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\models\api.py", line 430, in __call__
    return await self.set(*args, **kwargs)
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\models\api.py", line 398, in set
    return await self._call_api(
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\models\api.py", line 386, in _call_api
    return await api.call(self.api_provider, method, response_type)
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\models\api.py", line 318, in call
    raw_response = await self._call(api_provider, method)
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\models\api.py", line 304, in _call
    return await api_provider.call_api(
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\bot.py", line 320, in call_api
    return await self._adapter.call_api(api, *args, **kwargs)
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\adapters\websocket.py", line 236, in call_api
    return await self._recv(sync_id)
  File "C:\Users\b_z_b\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\adapters\websocket.py", line 165, in _recv
    raise exceptions.ApiError(data)
mirai.exceptions.ApiError: (500, '[ERROR 500]mirai 内部错误。', 'Timed out waiting for 5000 ms')

**Comment by BZBY** [comment]
没事了 重新搞了几次 发现qq能发信息了
