### ISSUE TITLE
[BUG]联网报错

### ISSUE THREAD

**Issue by Tudouuuuuu** [RockChinQ/qcg-installer#47]
**运行环境**
- 部署方式：
    手动部署 还是 自动部署
- 系统环境：
    e,g, Centos x64
- Python环境（仅手动部署填写）：
    e.g. Python 3.10.9

**描述漏洞**
什么时候发生的，mirai还是主程序，越详细越好

**完整报错信息**
完整的报错信息[2023-07-29 20:32:55.512] message.py (26) - [INFO] : [group_831299814]发送消息:介绍一下https://github.c...
[2023-07-29 20:32:55.512] host.py (356) - [DEBUG] : 触发事件: session_first_message_received (2)
[2023-07-29 20:32:55.512] host.py (398) - [DEBUG] : 事件 session_first_message_received (2) 处理完毕，返回值: {}
[2023-07-29 20:32:55.512] session.py (352) - [DEBUG] : cut_out: [
    {
        "role": "user",
        "content": "如果我之后想获取帮助，请你说“输入!help获取帮助”"
    },
    {
        "role": "assistant",
        "content": "ok, I'll follow your commands."
    },
    {
        "role": "user",
        "content": "介绍一下https://github.com/RockChinQ/qcg-installer"
    }
]
changable section tokens: 0
packed counts: []
session counts: []
[2023-07-29 20:32:55.512] proactor_events.py (630) - [DEBUG] : Using proactor: IocpProactor
[2023-07-29 20:32:55.528] util.py (60) - [DEBUG] : message='Request to OpenAI API' method=post path=https://api.chatanywhere.cn/v1/chat/completions
[2023-07-29 20:32:55.528] util.py (60) - [DEBUG] : api_version=None data='{"model": "gpt-4-32k", "messages": [{"role": "user", "content": "\\u5982\\u679c\\u6211\\u4e4b\\u540e\\u60f3\\u83b7\\u53d6\\u5e2e\\u52a9\\uff0c\\u8bf7\\u4f60\\u8bf4\\u201c\\u8f93\\u5165!help\\u83b7\\u53d6\\u5e2e\\u52a9\\u201d"}, {"role": "assistant", "content": "ok, I\'ll follow your commands."}, {"role": "user", "content": "\\u4ecb\\u7ecd\\u4e00\\u4e0bhttps://github.com/RockChinQ/qcg-installer"}], "functions": [{"description": "Call this function to search about the question before you answer any questions.\\n- Do not search through baidu.com at any time.\\n- If you need to search somthing, visit https://www.google.com/search?q=xxx.\\n- If user ask you to open a url (start with http:// or https://), visit it directly.\\n- Summary the plain content result by yourself, DO NOT directly output anything in the result you got.", "parameters": {"type": "object", "required": ["url", "brief_len"], "properties": {"url": {"type": "string", "description": "url to visit"}, "brief_len": {"type": "integer", "description": "max length of the plain text content, recommend 1024-4096, prefer 4096"}}}, "name": "Webwlkr-access_the_web"}], "temperature": 0.9, "top_p": 1, "frequency_penalty": 0.2, "presence_penalty": 1.0}' message='Post details'
[2023-07-29 20:32:57.547] connectionpool.py (1048) - [DEBUG] : Starting new HTTPS connection (1): api.github.com:443
[2023-07-29 20:32:58.455] connectionpool.py (546) - [DEBUG] : https://api.github.com:443 "GET /repos/RockChinQ/QChatGPT/releases HTTP/1.1" 200 None
[2023-07-29 20:32:58.455] main.py (321) - [INFO] : 当前已是最新版本
[2023-07-29 20:32:58.455] connectionpool.py (1048) - [DEBUG] : Starting new HTTPS connection (1): api.github.com:443
[2023-07-29 20:32:58.862] util.py (67) - [INFO] : message='OpenAI API response' path=https://api.chatanywhere.cn/v1/chat/completions processing_ms=None request_id=None response_code=500
[2023-07-29 20:32:58.862] util.py (67) - [INFO] : error_code=unmarshal_response_body_failed error_message='json: cannot unmarshal object into Go struct field DetailResponse.detail of type string' error_param=null error_type=aigc_api_error message='OpenAI API error received' stream_error=False
[2023-07-29 20:32:58.862] message.py (126) - [ERROR] : json: cannot unmarshal object into Go struct field DetailResponse.detail of type string {"error":{"message":"json: cannot unmarshal object into Go struct field DetailResponse.detail of type string","type":"aigc_api_error","param":"null","code":"unmarshal_response_body_failed"}} 500 {'error': {'message': 'json: cannot unmarshal object into Go struct field DetailResponse.detail of type string', 'type': 'aigc_api_error', 'param': 'null', 'code': 'unmarshal_response_body_failed'}} <CIMultiDictProxy('Date': 'Sat, 29 Jul 2023 12:32:58 GMT', 'Content-Type': 'application/json', 'Content-Length': '190', 'Connection': 'keep-alive', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'OPTIONS,GET,POST', 'Access-Control-Allow-Headers': '*', 'Access-Control-Max-Age': '6000', 'Vary': 'Origin', 'Vary': 'Access-Control-Request-Method', 'Vary': 'Access-Control-Request-Headers', 'CF-Cache-Status': 'DYNAMIC', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=a08s35JwWaR%2FGLWyzPkGFSku8LdjQ%2FOd6yJbRA%2F6U35FfJLh65kY5Z7ejn82cYNs4UzVp96OO3pq0KcyI5xfcAIPfKK7p7Bvv7DFsblzJUgaMPsd%2BZSJUieh3F2QkTjtjp4cukLU"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'CF-RAY': '7ee5632dde4e718c-LHR')>
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\QQ\QChatGPT\.\pkg\qqbot\message.py", line 43, in process_normal_message
    text = session.append(text_message)
  File "C:\Users\Administrator\Desktop\QQ\QChatGPT\.\pkg\openai\session.py", line 231, in append
    for resp in pkg.utils.context.get_openai_manager().request_completion(prompts):
  File "C:\Users\Administrator\Desktop\QQ\QChatGPT\.\pkg\openai\manager.py", line 54, in request_completion
    for resp in request:
  File "C:\Users\Administrator\Desktop\QQ\QChatGPT\.\pkg\openai\api\chat_completion.py", line 85, in __next__
    resp = self._req(**args)
  File "C:\Users\Administrator\Desktop\QQ\QChatGPT\.\pkg\openai\api\model.py", line 41, in _req
    raise exception
  File "C:\Users\Administrator\Desktop\QQ\QChatGPT\.\pkg\openai\api\model.py", line 25, in awrapper
    ret = await self.req_func(**kwargs)
  File "C:\Users\Administrator\Desktop\QQ\python\lib\site-packages\openai\api_resources\chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\QQ\python\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "C:\Users\Administrator\Desktop\QQ\python\lib\site-packages\openai\api_requestor.py", line 382, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
  File "C:\Users\Administrator\Desktop\QQ\python\lib\site-packages\openai\api_requestor.py", line 726, in _interpret_async_response
    self._interpret_response_line(
  File "C:\Users\Administrator\Desktop\QQ\python\lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.APIError: json: cannot unmarshal object into Go struct field DetailResponse.detail of type string {"error":{"message":"json: cannot unmarshal object into Go struct field DetailResponse.detail of type string","type":"aigc_api_error","param":"null","code":"unmarshal_response_body_failed"}} 500 {'error': {'message': 'json: cannot unmarshal object into Go struct field DetailResponse.detail of type string', 'type': 'aigc_api_error', 'param': 'null', 'code': 'unmarshal_response_body_failed'}} <CIMultiDictProxy('Date': 'Sat, 29 Jul 2023 12:32:58 GMT', 'Content-Type': 'application/json', 'Content-Length': '190', 'Connection': 'keep-alive', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'OPTIONS,GET,POST', 'Access-Control-Allow-Headers': '*', 'Access-Control-Max-Age': '6000', 'Vary': 'Origin', 'Vary': 'Access-Control-Request-Method', 'Vary': 'Access-Control-Request-Headers', 'CF-Cache-Status': 'DYNAMIC', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=a08s35JwWaR%2FGLWyzPkGFSku8LdjQ%2FOd6yJbRA%2F6U35FfJLh65kY5Z7ejn82cYNs4UzVp96OO3pq0KcyI5xfcAIPfKK7p7Bvv7DFsblzJUgaMPsd%2BZSJUieh3F2QkTjtjp4cukLU"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'CF-RAY': '7ee5632dde4e718c-LHR')>
[2023-07-29 20:32:58.956] manager.py (381) - [INFO] : 通知管理员:group_831299814会话处理异常:json: cannot unmarshal object into Go struct field DetailResponse.detail of type string {"error":{"message":"json: cannot unmarshal object into Go struct field DetailResponse.detail of type string","type":"aigc_api_error","param":"null","code":"unmarshal_response_body_failed"}} 500 {'error': {'message': 'json: cannot unmarshal object into Go struct field DetailResponse.detail of type string', 'type': 'aigc_api_error', 'param': 'null', 'code': 'unmarshal_response_body_failed'}} <CIMultiDictProxy('Date': 'Sat, 29 Jul 2023 12:32:58 GMT', 'Content-Type': 'application/json', 'Content-Length': '190', 'Connection': 'keep-alive', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'OPTIONS,GET,POST', 'Access-Control-Allow-Headers': '*', 'Access-Control-Max-Age': '6000', 'Vary': 'Origin', 'Vary': 'Access-Control-Request-Method', 'Vary': 'Access-Control-Request-Headers', 'CF-Cache-Status': 'DYNAMIC', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=a08s35JwWaR%2FGLWyzPkGFSku8LdjQ%2FOd6yJbRA%2F6U35FfJLh65kY5Z7ejn82cYNs4UzVp96OO3pq0KcyI5xfcAIPfKK7p7Bvv7DFsblzJUgaMPsd%2BZSJUieh3F2QkTjtjp4cukLU"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'CF-RAY': '7ee5632dde4e718c-LHR')>
[2023-07-29 20:32:58.956] proactor_events.py (630) - [DEBUG] : Using proactor: IocpProactor
[2023-07-29 20:32:59.078] network.py (15) - [DEBUG] : Network: requested url=http://localhost:5700/send_private_msg, by data_map={'user_id': 22101640318, 'message': '[bot]group_831299814会话处理异常:json: cannot unmarshal object into Go struct field DetailResponse.detail of type string {"error":{"message":"json: cannot unmarshal object into Go struct field DetailResponse.detail of type string","type":"aigc_api_error","param":"null","code":"unmarshal_response_body_failed"}} 500 {\'error\': {\'message\': \'json: cannot unmarshal object into Go struct field DetailResponse.detail of type string\', \'type\': \'aigc_api_error\', \'param\': \'null\', \'code\': \'unmarshal_response_body_failed\'}} <CIMultiDictProxy(\'Date\': \'Sat, 29 Jul 2023 12:32:58 GMT\', \'Content-Type\': \'application/json\', \'Content-Length\': \'190\', \'Connection\': \'keep-alive\', \'Access-Control-Allow-Credentials\': \'true\', \'Access-Control-Allow-Origin\': \'*\', \'Access-Control-Allow-Methods\': \'OPTIONS,GET,POST\', \'Access-Control-Allow-Headers\': \'*\', \'Access-Control-Max-Age\': \'6000\', \'Vary\': \'Origin\', \'Vary\': \'Access-Control-Request-Method\', \'Vary\': \'Access-Control-Request-Headers\', \'CF-Cache-Status\': \'DYNAMIC\', \'Report-To\': \'{"endpoints":[{"url":"https:\\\\/\\\\/a.nel.cloudflare.com\\\\/report\\\\/v3?s=a08s35JwWaR%2FGLWyzPkGFSku8LdjQ%2FOd6yJbRA%2F6U35FfJLh65kY5Z7ejn82cYNs4UzVp96OO3pq0KcyI5xfcAIPfKK7p7Bvv7DFsblzJUgaMPsd%2BZSJUieh3F2QkTjtjp4cukLU"}],"group":"cf-nel","max_age":604800}\', \'NEL\': \'{"success_fraction":0,"report_to":"cf-nel","max_age":604800}\', \'Server\': \'cloudflare\', \'CF-RAY\': \'7ee5632dde4e718c-LHR\')>', 'auto_escape': False}, and status=200, data={"data":null,"message":"请参考 go-cqhttp 端输出","msg":"SEND_MSG_API_ERROR","retcode":100,"status":"failed","wording":"请参考 go-cqhttp 端输出"}

[2023-07-29 20:32:59.081] process.py (161) - [INFO] : 回复[group_831299814]文字消息:[bot]err:出错了，请稍后再试
[2023-07-29 20:32:59.081] session.py (135) - [DEBUG] : group_831299814,lock release,<locked _thread.lock object at 0x000001220E297440>
[2023-07-29 20:32:59.081] session.py (137) - [DEBUG] : group_831299814,lock release successfully,<unlocked _thread.lock object at 0x000001220E297440>
[2023-07-29 20:32:59.081] proactor_events.py (630) - [DEBUG] : Using proactor: IocpProactor
[2023-07-29 20:32:59.113] connectionpool.py (546) - [DEBUG] : https://api.github.com:443 "GET /repos/RockChinQ/QChatGPT/contents/res/announcement.json HTTP/1.1" 200 770
[2023-07-29 20:33:00.006] ratelimit.py (55) - [DEBUG] : 清空当前分钟的对话次数
[2023-07-29 20:33:00.037] network.py (15) - [DEBUG] : Network: requested url=http://localhost:5700/send_group_msg, by data_map={'group_id': 831299814, 'message': '[CQ:reply,id=-430579058][bot]err:出错了，请稍后再试', 'auto_escape': False}, and status=200, data={"data":{"message_id":-1856843240},"message":"","retcode":0,"status":"ok"}

**Comment by Tudouuuuuu** [comment]
https://github.com/RockChinQ/qcg-installer/issues/47
