### ISSUE TITLE
ModuleNotFoundError: No module named 'openai.types'

### ISSUE THREAD

**Issue by youyi0218** [RockChinQ/qcg-installer#51]
**运行环境**
- 部署方式：
    手动部署
- 系统环境：
   Ubuntu22.0.4（proot安装）
- Python环境（仅手动部署填写）：
    Python 3.10.12

**描述漏洞**
原本可以正常运行，回复也正常。直接关闭主程序的终端之后，再打开就报错，提示ModuleNotFoundError: No module named 'openai.types'。尝试过重启系统，重新安装requirement，以及卸载openai库手动重装最新的openai和0.27.4版本（装最新的提示ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
chatgpt-tool-hub 0.4.6 requires openai~=0.27.4, but you have openai 1.6.1 which is incompatible.）都报错

**完整报错信息**
装requirement自带的和0.27.4版本会报错
![094287d33b37724732bbb71cf2839911](https://github.com/RockChinQ/qcg-installer/assets/135406843/b3be4626-9889-4c63-86b8-6a5f2ef971ff)
装最新的会报错2024-01-01 16:07:27 - ERROR    Multiple exceptions: [Errno 111] Connect call failed ('::1', 8080, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8080)
[2024-01-01 16:07:27.616] base.py (43) - [ERROR] : Multiple exceptions: [Errno 111] Connect call failed ('::1', 8080, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8080)
Traceback (most recent call last):
  File "/root/QChatGPT/main.py", line 287, in run_bot_wrapper
    qqbot.adapter.run_sync()
  File "/root/QChatGPT/pkg/qqbot/sources/yirimirai.py", line 120, in run_sync
    loop.run_until_complete(MiraiRunner(self.bot)._run())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/mirai/bot.py", line 240, in _run
    await self.startup()
  File "/usr/local/lib/python3.10/dist-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.10/dist-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "/usr/local/lib/python3.10/dist-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "/usr/local/lib/python3.10/dist-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/usr/local/lib/python3.10/dist-packages/websockets/legacy/client.py", line 651, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1084, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 8080, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8080)
[2024-01-01 16:07:27.637] main.py (324) - [ERROR] : 捕捉到未知异常:Multiple exceptions: [Errno 111] Connect call failed ('::1', 8080, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8080), 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue
Exception in thread Thread-2 (run_bot_wrapper):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QChatGPT/main.py", line 327, in run_bot_wrapper
    raise e
  File "/root/QChatGPT/main.py", line 287, in run_bot_wrapper
    qqbot.adapter.run_sync()
  File "/root/QChatGPT/pkg/qqbot/sources/yirimirai.py", line 120, in run_sync
    loop.run_until_complete(MiraiRunner(self.bot)._run())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/mirai/bot.py", line 240, in _run
    await self.startup()
  File "/usr/local/lib/python3.10/dist-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.10/dist-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "/usr/local/lib/python3.10/dist-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "/usr/local/lib/python3.10/dist-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/usr/local/lib/python3.10/dist-packages/websockets/legacy/client.py", line 651, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1084, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 8080, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8080)
但是终端不会自动结束

**Comment by RockChinQ** [comment]
openai依赖库必须高于 1.0.0

**Comment by youyi0218** [comment]
> openai依赖库必须高于 1.0.0

我试过安装最新的依赖库（应该是1.6.1）依然报错（在完整的报错信息的图片下面）

**Comment by RockChinQ** [comment]
你的报错日志是网络问题吧？到底是依赖库问题还是网络问题？

**Comment by RockChinQ** [comment]
依赖库装最新的肯定没错，网络问题是你没有正确配置mirai或者go-cqhttp，前往 https://q.rkcn.top 查看文档

**Comment by youyi0218** [comment]
> 你的报错日志是网络问题吧？到底是依赖库问题还是网络问题？

emmmm，openai版本更新前是依赖库问题，更新后现在成网络问题了（？）config.py的反代部署没问题（上午就用的这个代理就能跑），系统内也有网（gocq可以正常接收消息）

**Comment by RockChinQ** [comment]
你在跑gocq，但是你的报错是yirimirai的适配器报的，检查你的config.py第一个配置项是否写对

**Comment by youyi0218** [comment]
> 你在跑gocq，但是你的报错是yirimirai的适配器报的，检查你的config.py第一个配置项是否写对

好的我是铸币，重新clone的文件在配置config.py时下面的都配置了，唯独漏了最上面的yirimirai和gocq的选择了。现在机器人正常使用了，感谢大佬。
